---
dist: bionic

language: c

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

install:
  # Download and install recent cmake
  - |
      CMAKE_URL="http://www.cmake.org/files/v3.18/cmake-3.18.1-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

script:
  - date
  - mkdir .build && cd .build && cmake ..
  - make test

after_script:
  - date
